In [2]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from criar_planilhas import criar_planilha

dados = criar_planilha()

dados

,Country,Year,Industry,AI Adoption Rate (%),AI-Generated Content Volume (TBs per year),Job Loss Due to AI (%),Revenue Increase Due to AI (%),Human-AI Collaboration Rate (%),Top AI Tools Used,Regulation Status,Consumer Trust in AI (%),Market Share of AI Companies (%)
0,South Korea,2022,Media,44.29,33.09,16.77,46.12,74.79,Bard,Strict,40.77,18.73
1,China,2025,Legal,34.75,66.74,46.89,52.46,26.17,DALL-E,Strict,35.67,35.02
2,USA,2022,Automotive,81.06,96.13,10.66,45.60,39.66,Stable Diffusion,Moderate,54.47,22.76
3,France,2021,Legal,85.24,93.76,27.70,78.24,29.45,Claude,Moderate,51.84,1.93
4,France,2021,Gaming,78.95,45.62,17.45,1.05,21.70,Midjourney,Strict,41.77,21.41
...,...,...,...,...,...,...,...,...,...,...,...,...
195,Germany,2021,Automotive,89.44,52.98,48.47,12.14,30.60,DALL-E,Lenient,77.21,44.35
196,Germany,2020,Media,70.11,28.26,27.62,57.86,58.71,DALL-E,Strict,78.74,31.73
197,France,2023,Marketing,65.77,49.83,39.94,79.44,43.73,Synthesia,Lenient,81.58,14.62
198,Australia,2023,Automotive,45.35,20.49,33.21,50.50,41.73,Claude,Strict,47.42,43.11
199,South Korea,2020,Healthcare,10.53,20.97,23.64,34.27,45.67,Stable Diffusion,Moderate,58.52,33.37

In [3]:
dados.columns

Index(['Country', 'Year', 'Industry', 'AI Adoption Rate (%)',
       'AI-Generated Content Volume (TBs per year)', 'Job Loss Due to AI (%)',
       'Revenue Increase Due to AI (%)', 'Human-AI Collaboration Rate (%)',
       'Top AI Tools Used', 'Regulation Status', 'Consumer Trust in AI (%)',
       'Market Share of AI Companies (%)'],
      dtype='str')

In [4]:
dados.describe()

,Year,AI Adoption Rate (%),AI-Generated Content Volume (TBs per year),Job Loss Due to AI (%),Revenue Increase Due to AI (%),Human-AI Collaboration Rate (%),Consumer Trust in AI (%),Market Share of AI Companies (%)
count,200.000000,200.000000,200.00000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,2022.315000,54.265850,46.07260,25.788250,39.719450,54.102150,59.425150,26.569550
std,1.825496,24.218067,29.16122,13.901105,23.829545,19.247079,17.319668,14.023729
min,2020.000000,10.530000,1.04000,0.090000,0.140000,20.210000,30.120000,1.180000
25%,2021.000000,33.222500,20.32250,14.995000,17.907500,37.770000,44.755000,14.052500
50%,2022.000000,53.310000,44.32000,25.735000,42.100000,54.515000,59.215000,27.390000
75%,2024.000000,76.220000,71.62000,37.417500,58.697500,69.402500,74.885000,38.432500
max,2025.000000,94.760000,99.06000,49.710000,79.550000,88.290000,89.880000,49.280000

In [5]:
dados[['Industry', 'AI Adoption Rate (%)']]

       Industry  AI Adoption Rate (%)
0         Media                 44.29
1         Legal                 34.75
2    Automotive                 81.06
3         Legal                 85.24
4        Gaming                 78.95
..          ...                   ...
195  Automotive                 89.44
196       Media                 70.11
197   Marketing                 65.77
198  Automotive                 45.35
199  Healthcare                 10.53

[200 rows x 2 columns]

In [6]:
dados.groupby('Industry').mean(numeric_only=True)

,Year,AI Adoption Rate (%),AI-Generated Content Volume (TBs per year),Job Loss Due to AI (%),Revenue Increase Due to AI (%),Human-AI Collaboration Rate (%),Consumer Trust in AI (%),Market Share of AI Companies (%)
Industry,,,,,,,,
Automotive,2021.789474,54.887895,43.159474,28.916842,46.482632,55.906316,61.240000,29.591579
Education,2021.529412,57.028235,60.822941,26.142353,39.543529,58.875882,51.650000,22.835882
Finance,2021.928571,55.764286,37.545000,27.790000,36.257143,53.609286,56.180714,28.995714
Gaming,2022.962963,60.416296,44.470370,27.204074,33.234444,53.096296,61.342963,24.058148
Healthcare,2022.705882,55.734118,46.971765,25.579412,38.586471,55.227059,60.160588,29.642941
Legal,2022.823529,56.077647,59.902941,28.234118,41.824118,50.743529,57.789412,20.238824
Manufacturing,2021.722222,57.014444,49.809444,32.746111,42.807222,55.966667,58.272778,25.964444
Marketing,2022.631579,54.244211,37.197368,19.577895,36.813684,55.324211,58.671579,28.681579
Media,2021.903226,47.263226,38.174194,22.749032,43.719677,49.982903,61.759032,30.034516
Retail,2022.952381,47.905714,49.075238,21.846667,37.679524,55.412381,62.727619,24.599048

In [7]:
analise1 = dados.groupby('Industry')[['AI Adoption Rate (%)']].mean()

analise1

               AI Adoption Rate (%)
Industry
Automotive                54.887895
Education                 57.028235
Finance                   55.764286
Gaming                    60.416296
Healthcare                55.734118
Legal                     56.077647
Manufacturing             57.014444
Marketing                 54.244211
Media                     47.263226
Retail                    47.905714

In [8]:
# grafico1 = analise1.plot(kind='barh', figsize=(8,4), color='lightblue', xlim=(0,100), title='MÉDIA DE IMPLEMENTAÇÃO DE IA POR SETOR')

# grafico1

In [9]:
analise2 = dados.groupby('Industry')[['AI Adoption Rate (%)','Job Loss Due to AI (%)']].mean()

analise2

               AI Adoption Rate (%)  Job Loss Due to AI (%)
Industry
Automotive                54.887895               28.916842
Education                 57.028235               26.142353
Finance                   55.764286               27.790000
Gaming                    60.416296               27.204074
Healthcare                55.734118               25.579412
Legal                     56.077647               28.234118
Manufacturing             57.014444               32.746111
Marketing                 54.244211               19.577895
Media                     47.263226               22.749032
Retail                    47.905714               21.846667

In [10]:
# grafico2 = analise2.plot(
#     kind='bar',
#     color=['royalblue', 'crimson'],
#     figsize=(8,4), ylim=(0,100), 
#     edgecolor='white', 
#     title='RELAÇÃO IMPLEMENTAÇÃO DE IA COM PERDA DE EMPREGOS POR SETOR')

# grafico2

In [11]:
analise3 = dados.groupby('Country')[['AI Adoption Rate (%)']].mean()

analise3

             AI Adoption Rate (%)
Country
Australia               56.082000
Canada                  52.190000
China                   52.889048
France                  56.518333
Germany                 51.460000
India                   51.814583
Japan                   54.209545
South Korea             50.563500
UK                      64.692000
USA                     52.080952

In [12]:
analise6 = dados.groupby('Country')[['Job Loss Due to AI (%)', 'Human-AI Collaboration Rate (%)']].mean()

analise6

             Job Loss Due to AI (%)  Human-AI Collaboration Rate (%)
Country
Australia                 18.824000                        59.477333
Canada                    30.993125                        55.197500
China                     29.085238                        54.506667
France                    26.484167                        52.762083
Germany                   28.104118                        49.627059
India                     25.231250                        54.201667
Japan                     25.509545                        42.383182
South Korea               25.544500                        59.471500
UK                        27.134500                        58.268500
USA                       20.708571                        57.259524

In [13]:
# grafico3 = analise3.plot(kind='barh', color='orange', figsize=(8,4), xlim=(0,100), edgecolor='lightgray', title='MÉDIA DE IMPLEMENTAÇÃO DE IA POR PAÍS')

# grafico3

In [14]:
analise4 = dados.groupby(['Year', 'Industry'])['Job Loss Due to AI (%)'].mean().reset_index()
analise5 = analise4
filtro = analise4['Industry'].isin(['Automotive', 'Healthcare', 'Manufacturing'])
analise4 = analise4[filtro]

analise4

    Year       Industry  Job Loss Due to AI (%)
0   2020     Automotive               32.203333
4   2020     Healthcare               17.293333
6   2020  Manufacturing               34.681667
10  2021     Automotive               48.785000
14  2021     Healthcare               12.825000
16  2021  Manufacturing               30.005000
20  2022     Automotive               25.346667
24  2022     Healthcare               26.923333
26  2022  Manufacturing               33.230000
30  2023     Automotive               33.210000
34  2023     Healthcare               31.775000
36  2023  Manufacturing               17.230000
40  2024     Automotive               19.566667
43  2024     Healthcare               37.003333
45  2024  Manufacturing               29.220000
49  2025     Automotive               14.640000
53  2025     Healthcare               25.497500
55  2025  Manufacturing               42.980000

In [15]:
serie_temporal1 = analise5.pivot(index='Year', columns='Industry', values='Job Loss Due to AI (%)')

serie_temporal1

Industry,Automotive,Education,Finance,Gaming,Healthcare,Legal,Manufacturing,Marketing,Media,Retail
Year,,,,,,,,,,
2020,32.203333,29.918333,29.882000,46.780000,17.293333,28.503333,34.681667,22.993333,21.570,29.314000
2021,48.785000,26.181667,39.610000,35.500000,12.825000,37.670000,30.005000,22.690000,21.254,0.860000
2022,25.346667,32.070000,19.085000,15.090000,26.923333,33.220000,33.230000,47.250000,16.652,10.780000
2023,33.210000,22.340000,33.276667,30.750000,31.775000,11.083333,17.230000,21.613333,25.685,16.475000
2024,19.566667,NaN,16.465000,35.566667,37.003333,19.240000,29.220000,2.053333,35.630,49.580000
2025,14.640000,17.803333,29.110000,21.197500,25.497500,36.192000,42.980000,17.280000,12.465,21.831111

In [16]:
# grafico4 = serie_temporal1.plot(color=['dodgerblue', 'purple', 'firebrick'], figsize=(8,4), ylim=(0,100), title='SÉRIE TEMPORAL DE PERDA DE EMPREGOS POR SETOR')

# grafico4

In [17]:
serie_temporal2 = dados.groupby(['Country', 'Year'])[['AI Adoption Rate (%)', 'Revenue Increase Due to AI (%)', 'Market Share of AI Companies (%)']].mean()

serie_temporal2

                  AI Adoption Rate (%)  Revenue Increase Due to AI (%)  \
Country     Year
Australia   2020             34.727500                       57.635000
            2021             66.830000                       29.215000
            2022             84.280000                       41.255000
            2023             55.855000                       47.050000
            2024             78.210000                       76.760000
            2025             49.235000                       54.540000
Canada      2020             52.232000                       35.428000
            2021             49.720000                       66.780000
            2022             39.562500                       23.405000
            2023             46.725000                       38.415000
            2025             68.115000                       51.420000
China       2020             63.312857                       49.570000
            2021             37.916667                       42.683333
            2022             37.490000                       44.733333
            2023             58.233333                        8.010000
            2024             48.540000                       66.310000
            2025             54.505000                       48.735000
France      2020             63.973333                       32.355000
            2021             57.402000                       45.440000
            2022             46.645000                       39.645000
            2023             67.523333                       37.056667
            2024             43.508000                       32.830000
            2025             57.396667                       57.786667
Germany     2020             43.630000                       50.872000
            2021             55.352000                       29.898000
            2022             65.900000                       38.750000
            2023             57.765000                       34.417500
            2024             17.050000                       70.850000
India       2020             70.364000                       43.670000
            2021             54.205000                       45.690000
            2022             48.435000                       45.750000
            2023             39.040000                       28.930000
            2024             46.161667                       40.970000
            2025             46.305000                       35.731250
Japan       2020             26.650000                       35.515000
            2021             57.320000                       48.040000
            2022             42.856667                       30.780000
            2023             52.640000                       28.084000
            2024             79.606667                       42.530000
            2025             66.377500                       35.397500
South Korea 2020             23.294000                       49.238000
            2021             55.573333                       33.926667
            2022             59.475000                       26.235000
            2023             77.990000                       32.120000
            2024             36.586667                       29.126667
            2025             66.350000                       25.215000
UK          2020             67.936000                       37.724000
            2021             52.130000                       43.700000
            2022             57.326000                       28.896000
            2023             87.045000                       28.850000
            2024             80.030000                       48.415000
            2025             58.996667                       34.570000
USA         2020             30.046667                       50.053333
            2021             72.540000                       54.241667
            2022             72.890000                       53.260000
            2023             47.570000                       48.255000
            2024             32.000000                       40.670000
            2025             37.085000                       23.560000

                  Market Share of AI Companies (%)
Country     Year
Australia   2020                         15.650000
            2021                         25.295000
            2022                         15.570000
            2023                         23.482500
            2024                         49.040000
            2025                         34.005000
Canada      2020                         24.940000
            2021                         20.520000
            2022                         31.627500
            2023                         25.590000
            2025                         32.380000
China       2020                         25.791429
            2021                         28.956667
            2022                         35.800000
            2023                         17.546667
            2024                         24.810000
            2025                         29.025000
France      2020                         23.006667
            2021                         26.530000
            2022                         20.410000
            2023                         31.626667
            2024                         31.018000
            2025                         30.353333
Germany     2020                         25.818000
            2021                         24.490000
            2022                         28.530000
            2023                         40.897500
            2024                         45.600000
India       2020                         32.870000
            2021                         43.040000
            2022                         24.550000
            2023                         22.790000
            2024                         22.205000
            2025                         28.062500
Japan       2020                         29.515000
            2021                         37.180000
            2022                         29.628333
            2023                         28.542000
            2024                         11.266667
            2025                         27.427500
South Korea 2020                         26.052000
            2021                         23.656667
            2022                         23.905000
            2023                         23.246667
            2024                         42.953333
            2025                         24.742500
UK          2020                         23.832000
            2021                         34.063333
            2022                         19.766000
            2023                         22.900000
            2024                         45.195000
            2025                         15.486667
USA         2020                         15.316667
            2021                         21.288333
            2022                         29.053333
            2023                         32.300000
            2024                         22.310000
            2025                         15.476667

In [18]:
# serie_temporal2 = serie_temporal2.loc['UK']

# grafico5 = serie_temporal2.plot(kind='line', figsize=(8,4), ylim=(0,100), title="""SÉRIE TEMPORAL DA RELAÇÃO ENTRE IMPLEMENTAÇÃO DE IA, AUMENTO DE
# RECEITA E PARTICIPAÇÃO DE EMPRESAS DE IA NO MERCADO NO REINO UNIDO""")

# grafico5

In [19]:
serie_temporal3 = dados.groupby(['Industry', 'Year'])[['AI Adoption Rate (%)', 'Revenue Increase Due to AI (%)', 'Market Share of AI Companies (%)']].mean()

serie_temporal3

                    AI Adoption Rate (%)  Revenue Increase Due to AI (%)  \
Industry      Year
Automotive    2020             55.323333                       54.826667
              2021             67.940000                       38.560000
              2022             43.370000                       42.068333
              2023             45.350000                       50.500000
              2024             58.840000                       49.670000
              2025             92.960000                       25.170000
Education     2020             63.845000                       38.930000
              2021             54.836667                       43.955000
              2022             43.850000                       73.680000
              2023             82.820000                        1.440000
              2025             43.573333                       33.270000
Finance       2020             57.046000                       43.008000
              2021             14.760000                       76.520000
              2022             63.715000                       29.480000
              2023             64.653333                       10.946667
              2024             61.745000                       29.440000
              2025             35.830000                       65.360000
Gaming        2020             50.970000                       62.710000
              2021             63.216667                       24.070000
              2022             75.508000                       30.920000
              2023             60.057500                       45.802500
              2024             49.880000                       39.523333
              2025             54.195000                       29.227500
Healthcare    2020             33.263333                       46.053333
              2021             60.865000                       24.435000
              2022             54.066667                       28.793333
              2023             84.750000                       37.450000
              2024             51.410000                       57.163333
              2025             60.007500                       34.042500
Legal         2020             51.570000                       21.383333
              2021             55.430000                       74.670000
              2022             42.440000                       15.555000
              2023             63.580000                       20.356667
              2024             62.545000                       62.475000
              2025             57.408000                       56.078000
Manufacturing 2020             57.776667                       49.196667
              2021             49.685000                       37.250000
              2022             38.163333                       32.466667
              2023             78.570000                       47.610000
              2024             65.630000                       58.195000
              2025             78.270000                       32.475000
Marketing     2020             48.743333                       29.663333
              2021             60.993333                       63.470000
              2022             73.890000                       68.910000
              2023             44.235000                       28.585000
              2024             58.486667                       26.090000
              2025             62.223333                       33.790000
Media         2020             40.423333                       50.547778
              2021             60.416000                       49.750000
              2022             41.812000                       37.410000
              2023             60.118333                       31.533333
              2024             29.157500                       39.262500
              2025             56.435000                       59.165000
Retail        2020             46.850000                       39.162000
              2021             66.950000                       27.580000
              2022             63.023333                       29.843333
              2023             51.675000                       72.770000
              2024             26.630000                        1.750000
              2025             42.863333                       36.784444

                    Market Share of AI Companies (%)
Industry      Year
Automotive    2020                         23.386667
              2021                         39.370000
              2022                         24.043333
              2023                         43.110000
              2024                         48.780000
              2025                          9.470000
Education     2020                         18.286667
              2021                         24.453333
              2022                         25.070000
              2023                         17.290000
              2025                         29.803333
Finance       2020                         24.378000
              2021                         22.640000
              2022                         34.155000
              2023                         32.256667
              2024                         37.700000
              2025                         20.930000
Gaming        2020                         31.020000
              2021                         26.203333
              2022                         22.538000
              2023                         28.177500
              2024                         21.426667
              2025                         21.456250
Healthcare    2020                         20.653333
              2021                         11.030000
              2022                         37.046667
              2023                         31.665000
              2024                         33.560000
              2025                         36.190000
Legal         2020                         24.133333
              2021                         15.925000
              2022                          8.295000
              2023                         20.356667
              2024                         22.685000
              2025                         23.356000
Manufacturing 2020                         21.586667
              2021                         30.225000
              2022                         35.466667
              2023                         39.190000
              2024                         15.135000
              2025                         20.540000
Marketing     2020                         37.893333
              2021                         36.056667
              2022                         27.190000
              2023                         18.371667
              2024                         29.380000
              2025                         32.513333
Media         2020                         31.276667
              2021                         35.604000
              2022                         32.620000
              2023                         33.251667
              2024                         21.030000
              2025                         12.415000
Retail        2020                         18.344000
              2021                          8.090000
              2022                         16.283333
              2023                         29.325000
              2024                         48.530000
              2025                         28.971111

In [20]:
# serie_temporal3 = serie_temporal3.loc['Healthcare']

# grafico6 = serie_temporal3.plot(kind='line', figsize=(8,4), ylim=(0,100), title=("""SÉRIE TEMPORAL DA RELAÇÃO ENTRE IMPLEMENTAÇÃO DE IA, AUMENTO DE
# RECEITA E PARTICIPAÇÃO DE EMPRESAS DE IA NO MERCADO NA EDUCAÇÃO"""))

# grafico6

In [21]:
fig1 = px.bar(analise1.reset_index(), 
             x='AI Adoption Rate (%)', 
             y='Industry',
             orientation='h',
             title='MÉDIA DE IMPLEMENTAÇÃO DE IA POR SETOR',
             color_discrete_sequence=['skyblue'])

fig1.update_layout(
    xaxis_range=[0, 100],
    height=400,            
    width=800,            
    xaxis_title='Taxa de Adoção de IA (%)',
    yaxis_title='Setor',
    font=dict(
        color="white", 
        family="Arial",
        size=13,
        weight='bold'
    ),
    plot_bgcolor='rgba(0, 0, 0, 0)',
    paper_bgcolor='rgba(20, 20, 30, 1)'
)

# Mostrar o gráfico
fig1

In [22]:
fig2 = go.Figure()

# Barras azuis para Adoção de IA
fig2.add_trace(go.Bar(
    x=analise2['AI Adoption Rate (%)'],
    y=analise2.index,
    orientation='h',
    name='Adoção de IA',
    marker_color='royalblue'
))

# Barras vermelhas para Perda de Empregos
fig2.add_trace(go.Bar(
    x=analise2['Job Loss Due to AI (%)'],
    y=analise2.index,
    orientation='h',
    name='Perda de Empregos',
    marker_color='rgba(200, 50, 80, 1)'
))

In [23]:
fig2.update_layout(
    title='Relação entre Adoção de IA e Perda de Empregos por Setor',
    xaxis_title='Porcentagem (%)',
    yaxis_title='Setores',
    font=dict(
        color="white",            # Cor para ambos eixos
        family="Arial",
        size=13,
        weight='bold'
    ),
    xaxis_range=[0, 100],  # Fixa o eixo Y de 0 a 100%
    height=400,            
    width=800,   
    barmode='group',
    plot_bgcolor='rgba(0, 0, 0, 0)',
    paper_bgcolor='rgba(20, 20, 30, 1)'
)

fig2.show()

In [24]:
fig3 = px.bar(
    x=analise3['AI Adoption Rate (%)'],
    y=analise3.index,
    orientation='h',
    title='Média de Adoção de IA por País',
    color_discrete_sequence=['orange']
)

fig3.update_layout(
    xaxis_range=[0,100],
    height=400,            
    width=800,            
    xaxis_title='Taxa de Adoção de IA (%)',
    yaxis_title='País',
    font=dict(
        color="white", 
        family="Arial",
        size=13,
        weight='bold'
    ),
    plot_bgcolor='rgba(0, 0, 0, 0)',
    paper_bgcolor='rgba(20, 20, 30, 1)'
)

fig3.show()

In [25]:
fig7 = go.Figure()

fig7.add_trace(go.Bar(
    x=analise6.index,
    y=analise6['Human-AI Collaboration Rate (%)'],
    orientation='v',
    name='Colaboração Humano-IA',
    marker_color='lightgreen'
))

fig7.add_trace(go.Bar(
    x=analise6.index,
    y=analise6['Job Loss Due to AI (%)'],
    orientation='v',
    name='Perca de Emprego para IA',
    marker_color='indianred'
))

fig7.update_layout(
    yaxis_range=[0,100],
    yaxis_title='Porcentagem (%)',
    height=400,            
    width=800,            
    font=dict(
        color="white", 
        family="Arial",
        size=13,
        weight='bold'
    ),
    plot_bgcolor='rgba(0, 0, 0, 0)',
    paper_bgcolor='rgba(20, 20, 30, 1)'
)

In [26]:
fig4 = go.Figure()

fig4.add_trace(go.Scatter(
    x=serie_temporal1.index,
    y=serie_temporal1['Automotive'],
    name='Automotive',
    line=dict(color='royalblue', width=4)
))

fig4.add_trace(go.Scatter(
    x=serie_temporal1.index,
    y=serie_temporal1['Healthcare'],
    name='Healthcare',
    line=dict(color='red', width=4)
))

fig4.add_trace(go.Scatter(
    x=serie_temporal1.index,
    y=serie_temporal1['Manufacturing'],
    name='Manufactoring',
    line=dict(color='orange', width=4)
))

In [27]:
fig4.update_layout(
    yaxis_range=[0,100],
    title='Serie Temporal de Empregos Perdidos para IA por Setor',
    height=400,            
    width=800,            
    font=dict(
        color="white", 
        family="Arial",
        size=13,
        weight='bold'
    ),
    plot_bgcolor='rgba(0, 0, 0, 0)',
    paper_bgcolor='rgba(20, 20, 30, 1)'
)

fig4.show()

In [28]:
fig5 = go.Figure()

pais = 'UK'

fig5.add_trace(go.Scatter(
    x=serie_temporal2.loc[pais].index,
    y=serie_temporal2.loc[pais]['AI Adoption Rate (%)'],
    name='Adoção de IA (%)',
    line=dict(color='royalblue', width=4)
))

fig5.add_trace(go.Scatter(
    x=serie_temporal2.loc[pais].index,
    y=serie_temporal2.loc[pais]['Market Share of AI Companies (%)'],
    name='Participação de Empresas de IA no Mercado (%)',
    line=dict(color='red', width=4)
))

fig5.add_trace(go.Scatter(
    x=serie_temporal2.loc[pais].index,
    y=serie_temporal2.loc[pais]['Revenue Increase Due to AI (%)'],
    name='Aumento de Receita por Conta da IA (%)',
    line=dict(color='orange', width=4)
))

In [29]:
fig5.update_layout(
    yaxis_range=[0,100],
    title='Série Temporal Relação Adoção de IA, Aumento de Receita e Participação de Empresas de IA',
    height=400,            
    width=800,            
    font=dict(
        color='white', 
        family='Arial',
        size=11,
        weight='bold'
    ),
    plot_bgcolor='rgba(0, 0, 0, 0)',
    paper_bgcolor='rgba(20, 20, 30, 1)',
        legend=dict(
        orientation='h',
        yanchor="bottom",
        y=-0.5,
        xanchor="right",
        x=1.05
    )
)

fig5.show()

In [30]:
fig6 = go.Figure()

setor = 'Healthcare'

fig6.add_trace(go.Scatter(
    x=serie_temporal3.loc[setor].reset_index()['Year'],
    y=serie_temporal3.loc[setor]['AI Adoption Rate (%)'],
    name='Adoção de IA (%)',
    line=dict(color='royalblue', width=4)
))

fig6.add_trace(go.Scatter(
    x=serie_temporal3.loc[setor].reset_index()['Year'],
    y=serie_temporal3.loc[setor]['Market Share of AI Companies (%)'],
    name='Participação de Empresas de IA no Mercado (%)',
    line=dict(color='red', width=4)
))

fig6.add_trace(go.Scatter(
    x=serie_temporal3.loc[setor].reset_index()['Year'],
    y=serie_temporal3.loc[setor]['Revenue Increase Due to AI (%)'],
    name='Aumento de Receita por Conta da IA (%)',
    line=dict(color='orange', width=4)
))

In [31]:
fig6.update_layout(
    yaxis_range=[0,100],
    title='Série Temporal Relação Adoção de IA, Aumento de Receita e Participação de Empresas de IA',
    height=400,            
    width=800,            
    font=dict(
        color='white', 
        family='Arial',
        size=11,
        weight='bold'
    ),
    plot_bgcolor='rgba(0, 0, 0, 0)',
    paper_bgcolor='rgba(20, 20, 30, 1)',
        legend=dict(
        orientation='h',
        yanchor="bottom",
        y=-0.5,
        xanchor="right",
        x=1.05
    )
)

fig6.show()

In [32]:
analise7 = dados.groupby(['Country', 'Year'])[['Job Loss Due to AI (%)']].mean().reset_index()

serie_temporal4 = analise7.pivot(index='Year', columns='Country', values='Job Loss Due to AI (%)')

In [33]:
paises = ['USA', 'China']

grafico = go.Figure()

colors = ['red', 'lightcoral', 'darkred', 'firebrick', 'indianred']

cont = 0

for i in range(len(paises)):
    grafico.add_trace(go.Scatter(
        x=serie_temporal4.reset_index()['Year'],
        y=serie_temporal4[paises[cont]],
        name=paises[i],
        line=dict(color=colors[cont], width=4)
    )) 
    cont+=1

grafico.update_layout(
    yaxis_range=[0,100],
    title={
        'text': 'Serie Temporal de Empregos Perdidos para IA por País',
        'x': 0.5,
        'xanchor': 'center'
    },
    height=300,            
    width=600,            
    font=dict(
        color="white", 
        family="Arial",
        size=13
    ),
    plot_bgcolor='rgba(0, 0, 0, 0)',
    paper_bgcolor='rgba(20, 20, 30, 1)',
    legend=dict(
        orientation='h',
        y=-0.5,
        x=0
    )
)